guide/KV-stores-namespaces
ac524/anthonyteaches pull request #29
Opened 2022-05-30 20:07 UTC by kimberlym4488

Markdown detailing CF worker publish creating KV namespaces, route, and binding. 
Wrangler CLI commands and JS Crud methods for keys/values included.

2022-06-13 04:21 UTC, ac524 requested changes
@kimberlym4488 The table of contents is great. I'm not sure how much value the images and specific info about the FILES namespace are adding in the guide, so I think we should take that out for now.

Also, I think there are a number of images you've added in the assets folder I don't see being used, so those should be cleaned up.

2022-06-13 04:21 UTC, ac524 commented on .eslintrc.cjs
> +		FILES: readonly
These changes should be removed. They won't be relevant to our usage.

2022-06-13 04:21 UTC, ac524 commented on .gitignore
> +wrangler.toml
Let's remove this for now. I'll need this file committed for the CICD pipeline.

2022-06-13 06:05 UTC, kimberlym4488 commented
@ac524  should be all set!

2022-07-06 02:10 UTC, ac524 approved these changes

2022-07-06 02:10 UTC, merged